# Generated by Django 5.2.13 on 2026-04-23 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advisors', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='advisorhire',
            unique_together=set(),
        ),
    ]
