# Generated by Django 5.2.13 on 2026-04-18 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('commodity', 'Commodity'), ('stock', 'Stock'), ('crypto', 'Cryptocurrency')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
